services:
       vm1:
         build:
           context: ./app
           dockerfile: Dockerfile
         container_name: vm1
         ports:
           - "31001:3000"
         deploy:
           resources:
             limits:
               cpus: '1'
               memory: 512m
         networks:
           - ts-network

       vm2:
         build:
           context: ./app
           dockerfile: Dockerfile
         container_name: vm2
         ports:
           - "31002:3000"
         deploy:
           resources:
             limits:
               cpus: '1'
               memory: 1024m
         networks:
               - ts-network
networks:
      ts-network:
        driver: bridge
